def test_exceptions():
    pass